#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 22 11:06:48 2020

@author: erayturkel
"""

import matplotlib.pyplot as plt

means=result_sims['mean_gaps']
sds=result_sims['sdev_gaps']

means=means[1:,1:]
sds=sds[1:,1:]
x_axis=[r'$\bar{C}=0.5 D$', r'$\bar{C}=0.75 D$', r'$\bar{C}=D$']
plt.scatter(x_axis, means[0,:],  label='D=0.25 N')
plt.scatter(x_axis, means[1,:],  label='D=0.5 N')
plt.scatter(x_axis, means[2,:],  label='D=0.75 N')
#plt.errorbar(x_axis, means[3,:], yerr=1.96*sds[3,:], label='D=N')
plt.legend(loc='lower left');
plt.title(r'Average percentage gap to oracle value, as a function of $\bar C$ and $D$', fontdict=None, loc='center')
plt.show()